WIDTH = 360
HEIGHT = 648
MOVMENT_CONSTANT = 36
BOTTOM = 0

TOP = HEIGHT #this is top of screen
CENTER = WIDTH / 2 #this is center of screen

BLOCKLENGTH = 36

# PLAY_WIDTH = 263
# PLAY_HEIGHT = 73
# PLAY_BOUNDARYx = WIDTH/2 - 130
# PLAY_BOUNDARYy = HEIGHT/2

# QUIT_WIDTH = 204
# QUIT_HEIGHT = 69
# QUIT_BOUNDARYx = WIDTH/2 - 100
# QUIT_BOUNDARYy = HEIGHT/2 - 100